### ISSUE TITLE
Does this work? 

### ISSUE THREAD

**Issue by TheHamkerCat** [LvMalware/cf-proxy#1]
I'm getting these errors

 `http`
  ```sh
  $ bun proxy.js -a xxx -p 1080 http someInstanceHere.workers.dev
  
  $ curl --proxy http://localhost:1080 http://ipinfo.io -H "Authorization: xxx"
  
  >> curl: (52) Empty reply from server
  ```
  
  `socks`
  ```sh
  $ bun proxy.js -a xxx -p 1080 socks someInstanceHere.workers.dev
  
  $ curl --proxy socks5://localhost:1080 http://ipinfo.io -H "Authorization: xxx"
  
  >> curl: (97) connection to proxy closed
  ```

**Comment by LvMalware** [comment]
Hello @TheHamkerCat 

It does work. Unless the site is behind CloudFlare, in which case the workers [cannot connect to it](https://developers.cloudflare.com/workers/runtime-apis/tcp-sockets/#proxy-request-failed-cannot-connect-to-the-specified-address).

In your case, you are just typing the wrong address. Instead of `http://ipinfo.io`, try `https://ipinfo.io` (the HTTPS version of the website) and make sure your worker instance is running and the authorization token is correct.

Let me know if it works.

Best regards,

**Comment by LvMalware** [comment]
Since there was no response, I'm closing this issue. Feel free to open a new one if you need.
